const cfg = window.LEDGER_CONFIG || {};
const configured = cfg.supabaseUrl && !cfg.supabaseUrl.startsWith('YOUR_') && cfg.supabaseAnonKey && !cfg.supabaseAnonKey.startsWith('YOUR_');
const supabase = configured ? window.supabase.createClient(cfg.supabaseUrl, cfg.supabaseAnonKey) : null;
const $ = id => document.getElementById(id);
let currentUser = null, entryType = 'expense', entries = [];
const money = n => `¥${Number(n).toFixed(2)}`;
const today = new Date().toISOString().slice(0,10); $('date').value = today;
function showAuth(message=''){ $('auth-view').hidden=false; $('app-view').hidden=true; $('auth-message').textContent=message; }
function showApp(){ window.location.replace(new URL('preview.html', window.location.href).href); }
if(!configured) showAuth('请先在 config.js 填入 Supabase 配置，再发布网站。');
if(supabase) supabase.auth.getUser().then(({data,error})=> !error && data.user ? (currentUser=data.user,showApp()) : showAuth()).catch(()=>showAuth('暂时无法验证登录，请检查网络后重试。'));
$('auth-form').addEventListener('submit', async e=>{e.preventDefault(); if(!supabase)return; $('auth-message').textContent='正在处理…'; const email=$('email').value.trim(), password=$('password').value; let result=await supabase.auth.signInWithPassword({email,password}); if(result.error){result=await supabase.auth.signUp({email,password}); if(!result.error && !result.data.session) $('auth-message').textContent='注册成功，请检查邮箱后再登录。';} if(result.error) $('auth-message').textContent=result.error.message; else if(result.data.session){currentUser=result.data.user;showApp();}});
$('sign-out').addEventListener('click',async()=>{await supabase?.auth.signOut();currentUser=null;showAuth();});
document.querySelectorAll('.segmented button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.segmented button').forEach(x=>x.classList.remove('active'));b.classList.add('active');entryType=b.dataset.type;}));
$('entry-form').addEventListener('submit',async e=>{e.preventDefault();if(!supabase||!currentUser)return;const {error}=await supabase.from('entries').insert({user_id:currentUser.id,type:entryType,amount:Number($('amount').value),category:$('category').value,entry_date:$('date').value,note:$('note').value.trim()||null});if(error){$('entry-message').textContent=error.message;return}$('entry-form').reset();$('date').value=today;$('entry-message').textContent='已保存';setTimeout(()=>$('entry-message').textContent='',1800);loadEntries();});
async function loadEntries(){const {data,error}=await supabase.from('entries').select('*').order('entry_date',{ascending:false}).order('created_at',{ascending:false});if(error){$('entries').innerHTML=`<div class="empty">读取失败：${error.message}</div>`;return}entries=data||[];render();}
function render(){const month=today.slice(0,7), current=entries.filter(x=>x.entry_date.startsWith(month));const income=current.filter(x=>x.type==='income').reduce((a,x)=>a+Number(x.amount),0),expense=current.filter(x=>x.type==='expense').reduce((a,x)=>a+Number(x.amount),0);$('income-total').textContent=money(income);$('expense-total').textContent=money(expense);$('balance-total').textContent=money(income-expense);$('entry-count').textContent=`${entries.length} 笔`;const icons={餐饮:'🍜',交通:'🚇',购物:'🛒',居住:'🏠',娱乐:'🎮',医疗:'💊',工资:'💼',其他:'📦'};$('entries').innerHTML=entries.length?entries.map(x=>`<div class="entry"><div class="entry-icon">${icons[x.category]||'📦'}</div><div class="entry-main"><strong>${x.category}</strong><small>${x.entry_date}${x.note?' · '+x.note:''}</small></div><div class="entry-amount ${x.type}">${x.type==='income'?'+':'−'}${money(x.amount)}</div></div>`).join(''):'<div class="empty">还没有记录，先记下今天的第一笔吧。</div>';}
